version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  postgres_db:
    driver: local